#!/usr/bin/env bash
set -euo pipefail

MAVPROXY_BIN=${MAVPROXY_BIN:-mavproxy.py}
MAVPROXY_MASTER=${MAVPROXY_MASTER:-}
MAVPROXY_BAUD=${MAVPROXY_BAUD:-57600}
MAVPROXY_EXTRA_ARGS=${MAVPROXY_EXTRA_ARGS:-${MAVPROXY_EXTRA:-}}

if ! command -v "${MAVPROXY_BIN}" >/dev/null 2>&1